# Generated by Django 2.2.4 on 2019-11-05 19:52

from django.db import migrations, models
import mhep.v1.models.organisation


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_make_related_name_app_dependent'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=mhep.v1.models.organisation.Organisation.organisation_image_path),
        ),
    ]
